QAForum/Controllers/ForumController.cs
using QAForum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QAForum.Controllers
{
    public class ForumController : Controller
    {
        private IForumRepository forumRepository = null;

        public ForumController() : this(new SQLForumRepository())
        {

        }

        public ForumController(IForumRepository forumRepository)
        {
            this.forumRepository = forumRepository;
        }

        // GET: Forum
        [OutputCache(Duration = 10)]
        public ActionResult Index()
        {
            IEnumerable<Forum> forums = forumRepository.GetAllForums();

            ViewBag.Message = "QA Forums List";

            return View(forums);
        }

        // GET: Forum/Details/5
        public ActionResult Details(int id)
        {
            Forum forum = forumRepository.GetForumByID(id);

            ViewBag.Threads = forumRepository.GetThreadsByForum(id);

            return View(forum);
        }

        // GET: Forum/Create
        public ActionResult Create()
        {
            Forum forum = new Forum();

            return View(forum);
        }

        // POST: Forum/Create
        [HttpPost]
        public ActionResult Create(Forum forum)
        {
            try
            {
                // TODO: Add insert logic here
                forumRepository.AddForum(forum);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(forum);
            }
        }

        // GET: Forum/Edit/5
        public ActionResult Edit(int id)
        {
            Forum forum = forumRepository.GetForumByID(id);
            
            return View(forum);
        }

        // POST: Forum/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Forum forum)
        {
            try
            {
                // TODO: Add update logic here
                forumRepository.UpdateForum(forum);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(forum);
            }
        }

        // GET: Forum/Delete/5
        public ActionResult Delete(int id)
        {
            Forum forum = forumRepository.GetForumByID(id);
            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Forum forum = forumRepository.GetForumByID(id);
            try
            {
                // TODO: Add delete logic here
                forumRepository.DeleteForum(forum);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(forum);
            }
        }
    }
}

QAForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - QA Forum</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>@Html.Raw(@Html.ActionLink("[replacetext]", "Index", "Home",
new { area = "" },
new { @class = "navbar-brand"})
.ToHtmlString().Replace("[replacetext]", "<img src = \"/Content/images/forum.jpg\" alt=\"QA Forum logo\" />"))
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Forums", "Index", "Forum")</li>
                    <li>@Html.ActionLink("Post", "Index", "Post")</li>
                    <li>@Html.ActionLink("Thread", "Index", "Thread")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <a href="https://www.QA.com" target="_blank">QA training</a>
            <a href="https://www.QA.com/about-qa/blogs" target="_blank">QA Blogs</a>
            <p>&copy; @DateTime.Now.Year - QA</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>