QAForum/Models/Thread.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QAForum.Models
{
    public class Thread
    {
        public int ThreadID { get; set; }
        public int ForumID { get; set; }
        public string ThreadTitle { get; set; }
        public Guid OwnerID { get; set; }
    }
}

QAForum/Controllers/ThreadController.cs
using QAForum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QAForum.Controllers
{
    public class ThreadController : Controller
    {
        private IForumRepository forumRepository = null;

        public ThreadController() : this(new SQLForumRepository())
        {

        }

        public ThreadController(IForumRepository forumRepository)
        {
            this.forumRepository = forumRepository;
        }

        // GET: Thread
        [OutputCache(Duration = 10)]
        public ActionResult Index()
        {
            var threads = forumRepository.GetAllThreads();
            ViewBag.Message = "QA Forums list[Threads]";
            return View(threads);
        }

        public ActionResult GetPostsForThread(List<Post> posts)
        {
            if(posts.Count >  0 && posts != null)
            {
                return PartialView("~/Views/Post/PartialPostList.cshtml", posts);
            }
            else
            {
                ContentResult cvr = new ContentResult();
                cvr.Content = "There are no posts in this thread";
                return cvr;
            }

        }

        // GET: Thread/Details/5
        public ActionResult Details(int id)
        {
            var thread = forumRepository.GetThreadByID(id);
            ViewBag.Message = "Thread detail";
            ViewBag.Post = forumRepository.GetPostsByThread(id);
            return View(thread);
        }

        // GET: Thread/Create
        public ActionResult Create()
        {
            Thread thread = new Thread();

            return View(thread);
        }

        // POST: Thread/Create
        [HttpPost]
        public ActionResult Create(Thread thread)
        {
            try
            {
                // TODO: Add insert logic here
                forumRepository.AddThread(thread);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(thread);
            }
        }

        // GET: Thread/Edit/5
        public ActionResult Edit(int id)
        {
            Thread thread = forumRepository.GetThreadByID(id);

            return View(thread);
        }

        // POST: Thread/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Thread thread)
        {
            try
            {
                // TODO: Add update logic here
                forumRepository.UpdateThread(thread);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(thread);
            }
        }

        // GET: Thread/Delete/5
        public ActionResult Delete(int id)
        {
            Thread thread = forumRepository.GetThreadByID(id);
            return View(thread);
        }

        // POST: Thread/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Thread thread = forumRepository.GetThreadByID(id);
            try
            {
                // TODO: Add delete logic here
                forumRepository.DeleteThread(thread);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(thread);
            }
        }
    }
}

QAForum/Views/Thread/Create.cshtml
@model QAForum.Models.Thread

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thread</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ForumID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ForumID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ForumID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThreadTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThreadTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThreadTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QAForum/Views/Thread/Delete.cshtml
@model QAForum.Models.Thread

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Thread</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ForumID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForumID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThreadTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThreadTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QAForum/Views/Thread/Details.cshtml
@model QAForum.Models.Thread

@{
    ViewBag.Title = "Details";
}

<h2>@ViewBag.Message</h2>

<div>
    <h4>Thread</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ForumID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForumID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThreadTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThreadTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerID)
        </dd>

    </dl>

    <h3>Posts</h3>
    @Html.Action("GetPostsForThread", new { posts = (List<QAForum.Models.Post>)(ViewBag.Post)})
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ThreadID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QAForum/Views/Thread/Edit.cshtml
@model QAForum.Models.Thread

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thread</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ThreadID)

        <div class="form-group">
            @Html.LabelFor(model => model.ForumID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ForumID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ForumID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThreadTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThreadTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThreadTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QAForum/Views/Thread/Index.cshtml
@model IEnumerable<QAForum.Models.Thread>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Message</h2>

   @Html.Partial("PartialThreadList")

QAForum/Views/Thread/PartialThreadList.cshtml
@model IEnumerable<QAForum.Models.Thread>

<p>
    @Html.ActionLink("Create New", "Create", "Thread")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ForumID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThreadTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ForumID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThreadTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Thread", new { id = item.ThreadID }, null) |
                @Html.ActionLink("Details", "Details", "Thread", new { id = item.ThreadID }, null) |
                @Html.ActionLink("Delete", "Delete", "Thread", new { id = item.ThreadID }, null)
            </td>
        </tr>
    }

</table>